(declare (uses posix))
(declare (uses extras))

(display (seconds->local-time 30))
(display (current-directory))
(display (random 6))
(newline)
(display (random 6))
(newline)
(display (random 6))
(newline)
(display (random 6))
(newline)
(display (random 6))
(newline)
(display (random 6))
(newline)
(display (random 6))
(newline)
(display (random 6))
(newline)
(display (random 6))

